//<auto-generated />
namespace CsvToAvro.Claim
{
    using System.Runtime.Serialization;

    /// <summary>
    /// Used to serialize and deserialize Avro enum CsvToAvro.Claim.ClaimLeadIndicator.
    /// </summary>
    [DataContract(Namespace = "CsvToAvro.Claim")]
    public enum ClaimLeadIndicator
    {
        /// <summary>
        /// The Y symbol.
        /// </summary>
        [EnumMember]
        Y,

        /// <summary>
        /// The N symbol.
        /// </summary>
        [EnumMember]
        N,

    }
}