//<auto-generated />
namespace CsvToAvro.Claim
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record CsvToAvro.Claim.Policy.
    /// </summary>
    [DataContract(Namespace = "CsvToAvro.Claim")]
    public partial class Policy
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""CsvToAvro.Claim.Policy"",""fields"":[{""name"":""PolicyCode"",""type"":""string""},{""name"":""PolicyReference"",""type"":""string""},{""name"":""SectionCode"",""type"":""string""},{""name"":""SectionReference"",""type"":""string""},{""name"":""Section"",""type"":{""type"":""record"",""name"":""CsvToAvro.Claim.Section"",""fields"":[{""name"":""KeyIdPolis"",""type"":""string""},{""name"":""KeyDekkingsNummer"",""type"":""string""},{""name"":""Transaction"",""type"":{""type"":""record"",""name"":""CsvToAvro.Claim.Transaction"",""fields"":[{""name"":""KeyIdPolis"",""type"":""string""},{""name"":""KeyDekkingsNummer"",""type"":""string""},{""name"":""KeySchadeBoekingsNummer"",""type"":""string""},{""name"":""Payee"",""type"":""string""},{""name"":""RateOfExchange"",""type"":""string""},{""name"":""TransactionAuthorisationDate"",""type"":""long""},{""name"":""TransactionCurrencyCode"",""type"":""string""},{""name"":""TransactionDate"",""type"":""long""},{""name"":""TransactionReference"",""type"":""string""},{""name"":""TransactionSequenceNumber"",""type"":""string""},{""name"":""TransactionTypeCode"",""type"":""string""},{""name"":""TransactionTypeDescription"",""type"":""string""},{""name"":""TransactionComponent"",""type"":{""type"":""record"",""name"":""CsvToAvro.Claim.TransactionComponent"",""fields"":[{""name"":""KeyIdPolis"",""type"":""string""},{""name"":""KeyDekkingsNummer"",""type"":""string""},{""name"":""KeySchadeBoekingsNummer"",""type"":""string""},{""name"":""TransactionAmount"",""type"":""string""},{""name"":""TransactionComponentTypeCode"",""type"":""string""},{""name"":""TransactionComponentTypeDescription"",""type"":""long""}]}}]}}]}}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the PolicyCode field.
        /// </summary>
        [DataMember]
        public string PolicyCode { get; set; }
              
        /// <summary>
        /// Gets or sets the PolicyReference field.
        /// </summary>
        [DataMember]
        public string PolicyReference { get; set; }
              
        /// <summary>
        /// Gets or sets the SectionCode field.
        /// </summary>
        [DataMember]
        public string SectionCode { get; set; }
              
        /// <summary>
        /// Gets or sets the SectionReference field.
        /// </summary>
        [DataMember]
        public string SectionReference { get; set; }
              
        /// <summary>
        /// Gets or sets the Section field.
        /// </summary>
        [DataMember]
        public CsvToAvro.Claim.Section Section { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="Policy"/> class.
        /// </summary>
        public Policy()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Policy"/> class.
        /// </summary>
        /// <param name="policyCode">The policyCode.</param>
        /// <param name="policyReference">The policyReference.</param>
        /// <param name="sectionCode">The sectionCode.</param>
        /// <param name="sectionReference">The sectionReference.</param>
        /// <param name="section">The section.</param>
        public Policy(string policyCode, string policyReference, string sectionCode, string sectionReference, CsvToAvro.Claim.Section section)
        {
            this.PolicyCode = policyCode;
            this.PolicyReference = policyReference;
            this.SectionCode = sectionCode;
            this.SectionReference = sectionReference;
            this.Section = section;
        }
    }
}
