//<auto-generated />

using System.Runtime.Serialization;

namespace CsvToAvro.Utility.Models
{
    /// <summary>
    /// Used to serialize and deserialize Avro record CsvToAvro.Claim.Section.
    /// </summary>
    [DataContract(Namespace = "CsvToAvro.Claim")]
    public partial class Section
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""CsvToAvro.Claim.Section"",""fields"":[{""name"":""KeyIdPolis"",""type"":""string""},{""name"":""KeyDekkingsNummer"",""type"":""string""},{""name"":""Transaction"",""type"":{""type"":""record"",""name"":""CsvToAvro.Claim.Transaction"",""fields"":[{""name"":""KeyIdPolis"",""type"":""string""},{""name"":""KeyDekkingsNummer"",""type"":""string""},{""name"":""KeySchadeBoekingsNummer"",""type"":""string""},{""name"":""Payee"",""type"":""string""},{""name"":""RateOfExchange"",""type"":""string""},{""name"":""TransactionAuthorisationDate"",""type"":""long""},{""name"":""TransactionCurrencyCode"",""type"":""string""},{""name"":""TransactionDate"",""type"":""long""},{""name"":""TransactionReference"",""type"":""string""},{""name"":""TransactionSequenceNumber"",""type"":""string""},{""name"":""TransactionTypeCode"",""type"":""string""},{""name"":""TransactionTypeDescription"",""type"":""string""},{""name"":""TransactionComponent"",""type"":{""type"":""record"",""name"":""CsvToAvro.Claim.TransactionComponent"",""fields"":[{""name"":""KeyIdPolis"",""type"":""string""},{""name"":""KeyDekkingsNummer"",""type"":""string""},{""name"":""KeySchadeBoekingsNummer"",""type"":""string""},{""name"":""TransactionAmount"",""type"":""string""},{""name"":""TransactionComponentTypeCode"",""type"":""string""},{""name"":""TransactionComponentTypeDescription"",""type"":""long""}]}}]}}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the KeyIdPolis field.
        /// </summary>
        [DataMember]
        public string KeyIdPolis { get; set; }
              
        /// <summary>
        /// Gets or sets the KeyDekkingsNummer field.
        /// </summary>
        [DataMember]
        public string KeyDekkingsNummer { get; set; }
              
        /// <summary>
        /// Gets or sets the Transaction field.
        /// </summary>
        [DataMember]
        public Transaction[] Transaction { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="Section"/> class.
        /// </summary>
        public Section()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Section"/> class.
        /// </summary>
        /// <param name="keyIdPolis">The keyIdPolis.</param>
        /// <param name="keyDekkingsNummer">The keyDekkingsNummer.</param>
        /// <param name="transaction">The transaction.</param>
        public Section(string keyIdPolis, string keyDekkingsNummer, Transaction[] transaction)
        {
            this.KeyIdPolis = keyIdPolis;
            this.KeyDekkingsNummer = keyDekkingsNummer;
            this.Transaction = transaction;
        }
    }
}
