//<auto-generated />

using System.Runtime.Serialization;

namespace CsvToAvro.Utility.Models
{
    /// <summary>
    /// Used to serialize and deserialize Avro record CsvToAvro.Claim.Transaction.
    /// </summary>
    [DataContract(Namespace = "CsvToAvro.Claim")]
    public partial class Transaction
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""CsvToAvro.Claim.Transaction"",""fields"":[{""name"":""KeyIdPolis"",""type"":""string""},{""name"":""KeyDekkingsNummer"",""type"":""string""},{""name"":""KeySchadeBoekingsNummer"",""type"":""string""},{""name"":""Payee"",""type"":""string""},{""name"":""RateOfExchange"",""type"":""string""},{""name"":""TransactionAuthorisationDate"",""type"":""long""},{""name"":""TransactionCurrencyCode"",""type"":""string""},{""name"":""TransactionDate"",""type"":""long""},{""name"":""TransactionReference"",""type"":""string""},{""name"":""TransactionSequenceNumber"",""type"":""string""},{""name"":""TransactionTypeCode"",""type"":""string""},{""name"":""TransactionTypeDescription"",""type"":""string""},{""name"":""TransactionComponent"",""type"":{""type"":""record"",""name"":""CsvToAvro.Claim.TransactionComponent"",""fields"":[{""name"":""KeyIdPolis"",""type"":""string""},{""name"":""KeyDekkingsNummer"",""type"":""string""},{""name"":""KeySchadeBoekingsNummer"",""type"":""string""},{""name"":""TransactionAmount"",""type"":""string""},{""name"":""TransactionComponentTypeCode"",""type"":""string""},{""name"":""TransactionComponentTypeDescription"",""type"":""long""}]}}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }

        /// <summary>
        /// Gets or sets the KeyIdPolis field.
        /// </summary>
        [DataMember]
        public string KeyIdPolis { get; set; }

        /// <summary>
        /// Gets or sets the KeyDekkingsNummer field.
        /// </summary>
        [DataMember]
        public string KeyDekkingsNummer { get; set; }

        /// <summary>
        /// Gets or sets the KeySchadeBoekingsNummer field.
        /// </summary>
        [DataMember]
        public string KeySchadeBoekingsNummer { get; set; }

        /// <summary>
        /// Gets or sets the Payee field.
        /// </summary>
        [DataMember]
        public string Payee { get; set; }

        /// <summary>
        /// Gets or sets the RateOfExchange field.
        /// </summary>
        [DataMember]
        public string RateOfExchange { get; set; }

        /// <summary>
        /// Gets or sets the TransactionAuthorisationDate field.
        /// </summary>
        [DataMember]
        public long TransactionAuthorisationDate { get; set; }

        /// <summary>
        /// Gets or sets the TransactionCurrencyCode field.
        /// </summary>
        [DataMember]
        public string TransactionCurrencyCode { get; set; }

        /// <summary>
        /// Gets or sets the TransactionDate field.
        /// </summary>
        [DataMember]
        public long TransactionDate { get; set; }

        /// <summary>
        /// Gets or sets the TransactionReference field.
        /// </summary>
        [DataMember]
        public string TransactionReference { get; set; }

        /// <summary>
        /// Gets or sets the TransactionSequenceNumber field.
        /// </summary>
        [DataMember]
        public string TransactionSequenceNumber { get; set; }

        /// <summary>
        /// Gets or sets the TransactionTypeCode field.
        /// </summary>
        [DataMember]
        public string TransactionTypeCode { get; set; }

        /// <summary>
        /// Gets or sets the TransactionTypeDescription field.
        /// </summary>
        [DataMember]
        public string TransactionTypeDescription { get; set; }

        /// <summary>
        /// Gets or sets the TransactionComponent field.
        /// </summary>
        [DataMember]
        public TransactionComponent[] TransactionComponent { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Transaction"/> class.
        /// </summary>
        public Transaction()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Transaction"/> class.
        /// </summary>
        /// <param name="keyIdPolis">The keyIdPolis.</param>
        /// <param name="keyDekkingsNummer">The keyDekkingsNummer.</param>
        /// <param name="keySchadeBoekingsNummer">The keySchadeBoekingsNummer.</param>
        /// <param name="payee">The payee.</param>
        /// <param name="rateOfExchange">The rateOfExchange.</param>
        /// <param name="transactionAuthorisationDate">The transactionAuthorisationDate.</param>
        /// <param name="transactionCurrencyCode">The transactionCurrencyCode.</param>
        /// <param name="transactionDate">The transactionDate.</param>
        /// <param name="transactionReference">The transactionReference.</param>
        /// <param name="transactionSequenceNumber">The transactionSequenceNumber.</param>
        /// <param name="transactionTypeCode">The transactionTypeCode.</param>
        /// <param name="transactionTypeDescription">The transactionTypeDescription.</param>
        /// <param name="transactionComponent">The transactionComponent.</param>
        public Transaction(string keyIdPolis, string keyDekkingsNummer, string keySchadeBoekingsNummer, string payee, string rateOfExchange, long transactionAuthorisationDate, string transactionCurrencyCode, long transactionDate, string transactionReference, string transactionSequenceNumber, string transactionTypeCode, string transactionTypeDescription, TransactionComponent[] transactionComponent)
        {
            this.KeyIdPolis = keyIdPolis;
            this.KeyDekkingsNummer = keyDekkingsNummer;
            this.KeySchadeBoekingsNummer = keySchadeBoekingsNummer;
            this.Payee = payee;
            this.RateOfExchange = rateOfExchange;
            this.TransactionAuthorisationDate = transactionAuthorisationDate;
            this.TransactionCurrencyCode = transactionCurrencyCode;
            this.TransactionDate = transactionDate;
            this.TransactionReference = transactionReference;
            this.TransactionSequenceNumber = transactionSequenceNumber;
            this.TransactionTypeCode = transactionTypeCode;
            this.TransactionTypeDescription = transactionTypeDescription;
            this.TransactionComponent = transactionComponent;
        }
    }
}
