//<auto-generated />
namespace CsvToAvro.Claim
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record CsvToAvro.Claim.TransactionComponent.
    /// </summary>
    [DataContract(Namespace = "CsvToAvro.Claim")]
    public partial class TransactionComponent
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""CsvToAvro.Claim.TransactionComponent"",""fields"":[{""name"":""KeyIdPolis"",""type"":""string""},{""name"":""KeyDekkingsNummer"",""type"":""string""},{""name"":""KeySchadeBoekingsNummer"",""type"":""string""},{""name"":""TransactionAmount"",""type"":""string""},{""name"":""TransactionComponentTypeCode"",""type"":""string""},{""name"":""TransactionComponentTypeDescription"",""type"":""long""}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the KeyIdPolis field.
        /// </summary>
        [DataMember]
        public string KeyIdPolis { get; set; }
              
        /// <summary>
        /// Gets or sets the KeyDekkingsNummer field.
        /// </summary>
        [DataMember]
        public string KeyDekkingsNummer { get; set; }
              
        /// <summary>
        /// Gets or sets the KeySchadeBoekingsNummer field.
        /// </summary>
        [DataMember]
        public string KeySchadeBoekingsNummer { get; set; }
              
        /// <summary>
        /// Gets or sets the TransactionAmount field.
        /// </summary>
        [DataMember]
        public string TransactionAmount { get; set; }
              
        /// <summary>
        /// Gets or sets the TransactionComponentTypeCode field.
        /// </summary>
        [DataMember]
        public string TransactionComponentTypeCode { get; set; }
              
        /// <summary>
        /// Gets or sets the TransactionComponentTypeDescription field.
        /// </summary>
        [DataMember]
        public long TransactionComponentTypeDescription { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionComponent"/> class.
        /// </summary>
        public TransactionComponent()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionComponent"/> class.
        /// </summary>
        /// <param name="keyIdPolis">The keyIdPolis.</param>
        /// <param name="keyDekkingsNummer">The keyDekkingsNummer.</param>
        /// <param name="keySchadeBoekingsNummer">The keySchadeBoekingsNummer.</param>
        /// <param name="transactionAmount">The transactionAmount.</param>
        /// <param name="transactionComponentTypeCode">The transactionComponentTypeCode.</param>
        /// <param name="transactionComponentTypeDescription">The transactionComponentTypeDescription.</param>
        public TransactionComponent(string keyIdPolis, string keyDekkingsNummer, string keySchadeBoekingsNummer, string transactionAmount, string transactionComponentTypeCode, long transactionComponentTypeDescription)
        {
            this.KeyIdPolis = keyIdPolis;
            this.KeyDekkingsNummer = keyDekkingsNummer;
            this.KeySchadeBoekingsNummer = keySchadeBoekingsNummer;
            this.TransactionAmount = transactionAmount;
            this.TransactionComponentTypeCode = transactionComponentTypeCode;
            this.TransactionComponentTypeDescription = transactionComponentTypeDescription;
        }
    }
}
